### ISSUE TITLE
[REQ]: Optional config to display user friendly gamemode name

### ISSUE THREAD

**Issue by kus** [nickj609/GameModeManager#10]
Hi @nickj609 

Do you think it would be possible to add an optional user friendly gamemode display name lookup table so it converts the mapgroup raw value i.e. `dm-multicfg` to something more user friendly like "Deathmatch Multi Mode"?

It would be an optional setting, and when you are displaying the gamemode anywhere, you check if the key exists in the DisplayName config and display that or show the raw value if it doesn't exist.

**Comment by nickj609** [comment]
Hey @kus, that is a great idea and I think this could be accomplishable. I am wondering if there is a field in the gamemodes_server.txt that we might be able to override so when it's parsed it can be used as a 'Friendly' name for each map group/game mode. 

Then, for those wanted to create their own list, like is currently possible in the JSON config, there would just be an additional property mapping for the 'Friendly' name. I might be able to bake this in before the next release.

**Comment by kus** [comment]
@nickj609 I wonder if you can just create your own field.

I had a look to, looks like they have used `authorID` as free text. Doesn't make sense from configuration, but you could just put it in the instructions and I would be happy to use it.

```
"mg_de_facade"
		{
			"imagename"				"map-facade-overall"
			"nameID"				"#SFUI_Map_de_facade"
			"tooltipID"				"#SFUI_Map_Tooltip_Desc_Operation"
			"descriptionID"			"#SFUI_Map_Tooltip_Desc_facade"
			"authorID"				"TopHATTwaffle and maxgiddens"
			"name"					"mg_de_facade"
			"icontag"				"bomb"
			"show_medal_icon"		"5Operation$Community Season Five Summer 2014"
			"show_season_icon"		"season_4"
			"show_rich_presence"	"_vanguard"
			"grouptype"				"op_op05"
			"icon_image_path"		"map_icons/map_icon_de_facade"
			"maps"
			{
				"de_facade"		""
			}
		}
```

**Comment by nickj609** [comment]
@kus , it turns out you can add additional fields as long as it's in Valve Data Format (VDF).  I will be making a release in the next few hours with some awesome changes so stay on the lookout for this feature!
