### ISSUE TITLE
[Discussion] Bug Testing

### ISSUE THREAD

**Issue by mavproductions** [nickj609/GameModeManager#11]
Hey Nick,
I just compiled your recent build. Anything else I should test on Linux not on this list? I can maybe test Windows later today as time provides.

- Votes no longer succeed when only 1 person votes
        -This didn't work in my test. Still did a vote with Votes Enabled `true`, and GameMode `true` even though I was the only person in the server.
        
- A new admin settings menu (!settings)
        - NoBots works, bots only brought in a single bot for me. Might need more commands triggered to bring in bots if you're defaulting to a fill quota of 10
        
- Game mode rotations
        - Doesn't seem to rotate gamemodes even being set to `true` after the set Interval of `4`
        - Tested on Casual mode by doing the following:
             `!rcon mp_round_restart_delay 0`
             `!rcon mp_freezetime 0`
             `say !settings` --> Disable/Enable bots for 1 bot only to join(as configured currently!)
             `!rcon sv_cheats 1`
             `kill` --> until maxrounds limit met and RTV went through w map change
        - Did this 6 times
        
- Configuration options for map change / game mode delay
        - !gamesettings and !gamemodes didn't work for me

- Per game mode and per setting votes
        - Appears to work.
        - Any chance of adding secondary aliases using your GameModeManager.json schema? (so if my server members instinctively type `!aimmap` instead of `!aim` it can still work?
        
- All game mode and game settings votes (!gamesetting, !gamemode)
        - (See above)
        
- Configuration options for menu styles ("center" for center html (hud) menu, "chat" for chat menu.
        - Does `!maps` work for you in chat mode?
        - Seems to work otherwise for me, switched back to `center` and `!maps` started working for me.

Cheers,
-maV.

**Comment by nickj609** [comment]
Hey @mavproductions , thank you so much for all this testing! I believe I have addressed some of these issues in an unpublished commit.

I will be making an official release tonight with more information! I know I keep saying that but this time is for real haha. I just keep finding ways to improve it as I write.

**Comment by nickj609** [comment]
@mavproductions , a new release has been made. I will be marking this as completed. If you notice any other issues feel free to create another issue.
