### ISSUE TITLE
[Feature Request] Warmup Modes

### ISSUE THREAD

**Issue by Armageddon87270** [nickj609/GameModeManager#17]
Hi,

can we start certain cards in ar mode automaticités and then return to casual mode on other cards automatic ? how ?

**Comment by nickj609** [comment]
Hi again @Armageddon87270 , I apologize but I am not quite sure I understand your question.

I will be making a release today or tomorrow with some additional configuration options so that you can specify a schedule for specific game modes, as well as options for rotating between all maps across all game modes.

**Comment by Armageddon87270** [comment]
Hi, I would like that on a particular map or several it starts me in automatic ar mode ex: biome then the rest in casual mode

**Comment by nickj609** [comment]
Hey @Armageddon87270, I believe what you are asking is having the 'warmup' be a different game mode. Unfortuantely, I do not think this is possible with any out of the box solutions as of yet, and it is currently not a feature within this plugin. I am going on vacation, but I will keep this issue open as a potential enhancement to this plugin and will return to you with more information following some testing.

**Comment by Armageddon87270** [comment]
Hi,

Could you upgrade your plugins, spy on the name of the next maps and load the mode before changing maps, when loading maps your mode will be taken into account

ex: game_mode 0
game_ type 1

**Comment by nickj609** [comment]
@Armageddon87270 , I have been doing some testing, which has been very promising. The next release should contain the addition of warmup modes with the ability to set warmup modes on a per mode basis (all maps in mode) and also on a per-map basis (MapExec) using the css_warmupmode console command for the configs. 

Keep on the lookout :)

**Comment by nickj609** [comment]
This feature has been added to the latest release.

https://github.com/nickj609/GameModeManager/releases/tag/v1.0.46
