### ISSUE TITLE
[Bug] !map listings not reflecting actual mapgroups

### ISSUE THREAD

**Issue by mavproductions** [nickj609/GameModeManager#2]
Hey there,

So your plugin is definitely starting to load map lists with my groups lately.

I use [this configuration](https://github.com/mavproductions/cs2-modded-server/blob/master/game/csgo/addons/counterstrikesharp/configs/plugins/GameModeManager/GameModeManager.json) of your plugin, my [gamemode_server.txt here](https://github.com/mavproductions/cs2-modded-server/blob/master/game/csgo/gamemodes_server.txt) and an example of my [prac.cfg here](https://github.com/mavproductions/cs2-modded-server/blob/master/game/csgo/cfg/prac.cfg) or [casual.cfg for that matter](https://github.com/mavproductions/cs2-modded-server/blob/master/game/csgo/cfg/casual.cfg)

I noticed this odd occurrence where I reboot my server and the map listings are bugged out, and sometimes don't pick up. However if I delete the GameModeManager.json file and let it rebuild, then repaste my custom list, modes like prac, and aim begin to list again properly.

Casual however seems to not work in general and I'm not sure why.

It's a really odd issue. If you need particular logs, this might give me an excuse to fix my sv_logfile issues and get a full server log for you if needed. I'm not sure what's going on.

It's working a LOT better than on the weekend when I was getting no maplistings at all.

Really appreciate you making this plugin regardless. It works really nice. :)

Cheers,

**Comment by mavproductions** [comment]
I think I fixed it. It was just a lot of case-sensitive issues since I want to keep capitalized Mode options instead of all lowercase (or whatever mg/mode.cfg is labeled as. Will confirm once I complete my testing.

**Comment by nickj609** [comment]
Hey @mavproductions I was hoping you would reach out because I was in unable to get in touch with you on Discord. Also, thanks for flagging this bug.

I should be able to build some logic into the plugin that compensates for case-related issues and I can make a note of this in the readme file. 

How is everything going since you got it working? I know Kus mentioned creating a custom RTV plugin for game modes and settings and was thinking about incorporating this. However, I may reach out to them directly to see if this plugin can be repurposed for that project. 

Still getting the hang of GitHub branches/pull requests and whatnot so apologies on the pull request being closed out prematurely.

**Comment by nickj609** [comment]
@mavproductions, I believe I have addressed several of these issues in the latest release. Can you check and see if any of the above issues persist? If so, a copy of the logs would be great!

https://github.com/nickj609/GameModeManager/releases/tag/v1.0.3

**Comment by mavproductions** [comment]
Awesome. You bet! Thanks so much!

**Comment by mavproductions** [comment]
So far I haven't run into as many issues. I think if I exec a gamemode change in rcon instead of !mode, it might not always bring up the right mode. 

I can't remember exactly how to reproduce it but I'll be experimenting more over the weekend. 

Thanks again btw for all of this!

PS. Any tips on adding extend map by x minutes on RTV? The one your repo recommends doesn't seem to have that option, which is super important to me. I already opened an issue on the RTV repo.

**Comment by mavproductions** [comment]
I think there might be a misunderstanding.

Basically at the top of the vote I would like an option for users to have a value pulled from the RTV (or GameModeManager) for extending the map +15minutes or whatever the extend map value is.

This would ideally be an RTV option at the very top (Choice #1) so any user could extend a map if they need more time, be it KZ/surf/retakes w friends, BHop, etc.
