### ISSUE TITLE
[Feature] Using !map or !maps followed by the map to switch and skip the menu

### ISSUE THREAD

**Issue by mavproductions** [nickj609/GameModeManager#3]
Hey @nickj609 

I think it would be neat if some maps (maybe starting with default maps if it's easier) so users can use `!map de_mirage` or !maps de_mirage` to quickly switch the map to bypass the menu altogether.

Since my server is coming from CS2-Ultimate-Mapchooser, some of my users remember `!map <mapHere>`, so they might get confused with the implementation of GameModeManager.

No worries if you don't have the time, but really appreciate the plugin regardless.

Cheers,

**Comment by nickj609** [comment]
This is a great request! I'm going to add it to the list of features. I create an object called map that separates the name from the workshop ID so it should be a quick addition.

**Comment by nickj609** [comment]
Feature added to latest release:

https://github.com/nickj609/GameModeManager/releases/tag/v1.0.3
