### ISSUE TITLE
[Help - Optimization] Rcon exec <mode> vs !mode load-times

### ISSUE THREAD

**Issue by mavproductions** [nickj609/GameModeManager#4]
Hey @nickj609 

Hope you're enjoying your weekend, just have a quick thought.

When I compare rcon exec times vs. !mode load-times, there's a +5second difference with !mode. Any reason for the additional buffer? Is it required?

It's a very small thing, but if it doesn't make a difference, perhaps it could be an option in the GameModeManager.json so if server-operators wish to be able to have time to read the chat output, that's cool. I personally would like to rely on server logs if possible, and change as instant as possible.

Thanks for entertaining my ideas, sorry for the spam. 

😊 Take care,

**Comment by nickj609** [comment]
@mavproductions, yes you are correct! I added a 5-second delay for in-game messaging. I could make this configurable in the JSON though.

**Comment by mavproductions** [comment]
Very awesome!!! Thanks a lot! :):):)

**Comment by nickj609** [comment]
Hey @mavproductions, don't worry I haven't forgot about you! I actually have a new version coming out soon. Just doing some testing to make sure it's working as intended. If you are curious, its in the v1.0.4 branch, although you would have to know how to compile it yourself until its released.

**Comment by mavproductions** [comment]
I'm just testing what I presume to be 1.0.5. Going from version 1.0.3 and finally seeing the delay feature! Lovely stuff!

**Comment by mavproductions** [comment]
One thing that might be neat to add to the Custom-Votes plugin, is if the server only has 1 player in it, if a player votes for a map, it's an instant switch. 

@kus made a really nice custom-votes template where `!aim` for example would start a vote for aim map mode. When there is one player in the server, it won't switch right away. 

I'm curious if my suggestion is an optimized approach in this type of circumstance.
