### ISSUE TITLE
[Feature] Game Mode Rotations .json option for Multi-Mod server variety

### ISSUE THREAD

**Issue by mavproductions** [nickj609/GameModeManager#5]
Hey @nickj609,

An idea came to my head about this plugin. I think it would be neat if your mod/plugin could introduce a mode rotation. Compatibility with other plugins and their logic would be paramount, as the last thing we would want is someone working to perfect a KZ/surf/Bhop run, or an interrupted MatchZy10man/prac session, or [OpenPrefirePrac](https://github.com/lengran/OpenPrefirePrac) session.

I know this might be super conditional and hard to implement, but just again a random idea that came up.

Again, enjoy your weekend, and as always take your time 😀

Thanks,

**Comment by nickj609** [comment]
Hey @mavproductions, this doesn't seem too difficult to implement. For example, I could create a configuration option that would be used to change the game mode after X map rotations to a random game mode.  But, this would most likely be supplementary for those who aren't using an RTV plugin (i.e. the RTV.Enabled config is set to false). 

However, I was also thinking about adding options like !extend or !gamemode to initiate a vote to extend the map or change the game mode.  This would essentially work on top of other RTV plugins and wouldn't be included in the end-of-map vote. 

I like this approach because it's less dependent on any plugin-specific configurations while still offering some level of compatibility with different types of RTV plugins.

**Comment by mavproductions** [comment]
Sorry for the confusion. I forgot to mention a key detail to my idea

My original idea/main point I meant to say was - when the server is empty, feel free to change mode every x minutes. Not exactly a mode RTV, but a mode RTV is still a cool idea.

For my server as of now, it's mainly just for people to use for competitive style practice mainly, unless we want a "fun night/session" random. RTV is nice for surf and stuff, but right now extending x time is important as I don't want RTV to force map changes on ppl, if their in the middle of something.

Sorry for my lack of articulation. I think the ideas you mentioned are good as well and setting I would definitely use too. I would just hope they all come w toggles.

Cheers!

**Comment by mavproductions** [comment]
Hey @nickj609 !

Just curious about updates regarding this. No worries if you've been busy. :)

**Comment by nickj609** [comment]
Hey @mavproductions, don't worry I haven't forgot about you! I actually have a new version coming out soon. Just doing some testing to make sure it's working as intended. If you are curious, its in the v1.0.4 branch, although you would have to know how to compile it yourself until its released. 

Regarding this particular request, I found it difficult to implement an automatic game mode rotation when the player count is 0, but I do however have the features added to the new build that allows users to initiate a vote to change the game mode as well as a settings menu for changing settings, like enabling gravity, etc.

**Comment by mavproductions** [comment]
Woo! Just seeing that now wow! I do know how to compile so I will add it into my server and let you know if I run into any hiccups! Thanks for giving my head a shake :D

**Comment by nickj609** [comment]
@mavproductions , you are very welcome! I haven't had a chance to test it as of yet so apologies if it doesn't work as expected. It does compile properly though haha.

**Comment by mavproductions** [comment]
No sweat. I like the idea of gamemode voting still and have some time to spare here and there to help w bug reporting.

**Comment by mavproductions** [comment]
Yo! Just compiled your newest build! Looks great with `!extend`! love what work you've been doing with it! :)

**Comment by nickj609** [comment]
@mavproductions, that is great to hear! I have been doing a little here and there while studying for my AZ104. However, I have been struggling to fully implement the extend feature so it will most likely be in the next iteration (1.0.5).

**Comment by mavproductions** [comment]
Awesome to hear about your studies about AZ104. Best of luck! I've been considering similar certs as well as of late.

`!extend` is helpful as is now, but if you integrate it with RTV, that's really incredible as well.
