### ISSUE TITLE
[EROR] (plugin:GameModeManager) Incomplete VDF data.

### ISSUE THREAD

**Issue by 4fc7c8f789** [nickj609/GameModeManager#6]
Hey,

Unfortunately I can't get the plugin to work on my gameserver (not configured with kus's "cs2-modded-server"). Any ideas?
See below:

### **-- When loading plugin**

**css_plugins reload "GameModeManager"**
18:04:32 [INFO] (cssharp:PluginContext) Unloading plugin GameModeManager
18:04:32 [INFO] (cssharp:PluginContext) Finished unloading plugin GameModeManager
18:04:32 [INFO] (cssharp:PluginContext) Loading plugin GameModeManager
18:04:32 [INFO] (plugin:GameModeManager) Parsing map group file /home/container/game/csgo/gamemodes_server.txt.

**18:04:32 [EROR] (plugin:GameModeManager) Incomplete VDF data.**

18:04:32 [INFO] (plugin:GameModeManager) Creating mode menu.
18:04:32 [INFO] (cssharp:PluginContext) Finished loading plugin GameModeManager

### **-- When loading mapgroup**
Setting mapgroup to 'mg_custom'
18:03:26 [INFO] (plugin:GameModeManager) Map group command detected!

**18:03:26 [INFO] (plugin:GameModeManager) New mapgroup could not be found. Setting default map group.**

18:03:26 [INFO] (plugin:GameModeManager) New MapGroup is mg_active.
18:03:26 [INFO] (plugin:GameModeManager) Updating map list for RTV plugin.
18:03:26 [INFO] (plugin:GameModeManager) Reloading RTV plugin.
18:03:26 [INFO] (plugin:GameModeManager) Updating map menu.

**Could not reload plugin "/home/container/game/csgo/addons/counterstrikesharp/plugins/RockTheVote/RockTheVote.dll"**

--

Resources and logs:
- [GameModeManager.json](https://github.com/nickj609/GameModeManager/files/14897902/GameModeManager.json)
- [gamemodes_server.txt](https://github.com/nickj609/GameModeManager/files/14897904/gamemodes_server.txt)

**Comment by nickj609** [comment]
Hey @4fc7c8f789, sorry to hear you are experiencing issues with the plugin. I took the liberty of reviewing your gamemodes_server.txt file and noticed a syntax issue. 

For the map group "mg_custom" you are missing a set of double quotations ("") following the gg_simpons map.

Original

```
		"mg_custom"
		{
			"name"					"mg_custom"
			"maps"
			{
				"workshop/3070923343/fy_pool_day"		""
				"workshop/3084291314/aim_map"		""
				"workshop/3070260370/aim_map_s2r"		""
				"workshop/3082605693/aim_long_dust"		""
				"workshop/3159212000/awp_crazy_box_zk"		""
				"workshop/3139172262/aim_redline_arena"		""
				"workshop/3078701726/aim_ak-colt"		""
				"workshop/3077655898/awp_lego"		""
				"workshop/3084690440/fy_poolparty_oser"		""
				"workshop/3157786856/aim_deagle_sand"		""
				"workshop/3081158339/aim_crazyjump_simpsons_v2"		""
				"workshop/3070238628/fy_iceworld"		""
				"workshop/3071818846/de_rats_kitchoon"		""
				"workshop/3161693626/de_rats_1337_v2"		""
				"workshop/3072759265/de_drachenschanze"		""
				"workshop/3186779271/minecraft_hungergames"	""
				"workshop/3179141529/trump3t_legoland"	""
				"workshop/3109232789/gg_simpsons_vs_flanders_v2"	
				"workshop/3071118054/fy_desert"		""
			}
		}
```

Fixed:

```
		"mg_custom"
		{
			"name"					"mg_custom"
			"maps"
			{
				"workshop/3070923343/fy_pool_day"		""
				"workshop/3084291314/aim_map"		""
				"workshop/3070260370/aim_map_s2r"		""
				"workshop/3082605693/aim_long_dust"		""
				"workshop/3159212000/awp_crazy_box_zk"		""
				"workshop/3139172262/aim_redline_arena"		""
				"workshop/3078701726/aim_ak-colt"		""
				"workshop/3077655898/awp_lego"		""
				"workshop/3084690440/fy_poolparty_oser"		""
				"workshop/3157786856/aim_deagle_sand"		""
				"workshop/3081158339/aim_crazyjump_simpsons_v2"		""
				"workshop/3070238628/fy_iceworld"		""
				"workshop/3071818846/de_rats_kitchoon"		""
				"workshop/3161693626/de_rats_1337_v2"		""
				"workshop/3072759265/de_drachenschanze"		""
				"workshop/3186779271/minecraft_hungergames"	""
				"workshop/3179141529/trump3t_legoland"	""
				"workshop/3109232789/gg_simpsons_vs_flanders_v2"	""	
				"workshop/3071118054/fy_desert"		""
			}
		}
```

**Comment by nickj609** [comment]
Hey @4fc7c8f789 are you still experiencing issues with the plugin?

**Comment by 4fc7c8f789** [comment]
Hey @nickj609 - sorry for coming back on this so late! Everything is working smoothly now :)
