### ISSUE TITLE
[Build Error] 1.0.4

### ISSUE THREAD

**Issue by mavproductions** [nickj609/GameModeManager#9]
Hey Nick! 

Don't mean to bother you as I imagine you're still busy and enjoying the season. Hope you've been well.

I'm having issues building your recent commit. Getting a lot of gameloop and vproperty errors.

I tried building as is and using "Microsoft.NET.UpgradeAssistant" to go to .net V8 and had no luck.

Any pointers?

As always I appreciate the work you've done so far with this repo. Really works nice 🙂🙂

**Comment by nickj609** [comment]
Hey @mavproductions, thank you for pointing this out. I was trying to recover some lost changes and ended up having to merge and purge all other branches, which resulted in an incomplete build. I will be making a commit right after this post with some final touches. 

Once again, these changes haven't been tested yet on my server, but they compile and I will be doing some testing tomorrow. However, keep a lookout for these changes in the new build:

- Votes no longer succeed when only 1 person votes
- A new admin settings menu (!settings)
- Game mode rotations
- Configuration options for map change / game mode delay
- Per game mode and per setting votes (e.g !aim, !bhop)
- All game mode and game settings votes (!gamesetting, !gamemode)
- Configuration options for menu styles ("center" for center html (hud) menu, "chat" for chat menu.

**Comment by mavproductions** [comment]
Niiice this all looks really interesting. Love how you made gamemode alias votes native to the plugin. If a single player is in the server, and types !awp for example, will it skip the vote and just run it?

**Comment by nickj609** [comment]
Yeah, I believe so. I adapted the same configuration that @kus used in his JSON, as it's coincidentally an integration of the same plugin, but through shared libraries. So for this reason, I am hoping the behavior is identical.

**Comment by kus** [comment]
Great work @nickj609, that was going to be my one question that @mavproductions asked, based on the above `Votes no longer succeed when only 1 person votes`. If it is only 1 person in the server, it would be good if it did change.

**Comment by nickj609** [comment]
@kus, that makes complete sense! I must have gotten my wires crossed because now that I am reviewing the changes it looks like I had a 51% requirement and changing it to 50% was what I believe I had to change when reviewing your configuration.

**Comment by kus** [comment]
51% should still work if it is only 1 player as if they vote it's 100% of players voted yes?

**Comment by kus** [comment]
@nickj609 in his code he has `if (Vote.MinVotePercentage < 0 || winningOption.Value.Count >= totalVotes * Vote.MinVotePercentage / 100)`

https://github.com/imi-tat0r/CS2-CustomVotes/blob/master/CS2-CustomVotes/Models/ActiveVote.cs#L55C8-L56C34

So `-1` will make the vote change no matter what.

So you should be able to use `51` to make it change if 51% of people vote for it. He uses `50` in his example https://github.com/imi-tat0r/CS2-CustomVotes/blob/master/CS2-CustomVotes/PluginConfig.cs#L37
